<a href="https://colab.research.google.com/github/Junhojuno/pytorch-tutorial/blob/master/pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is Pytorch?
- Numpy 대체 + GPU연산력사용
- 유연성 및 속도제공하는 딥러닝 연구 플랫폼

In [0]:
from __future__ import print_function
import torch

In [2]:
# 5 x 3 matrix생성, 2D Tensor
# 초기화 되지 않는 행렬
x = torch.Tensor(5,3)
print(x) 

tensor([[1.1514e-35, 0.0000e+00, 3.7835e-44],
        [0.0000e+00,        nan, 6.4460e-44],
        [1.3733e-14, 6.4069e+02, 4.3066e+21],
        [1.1824e+22, 4.3066e+21, 6.3828e+28],
        [3.8016e-39, 5.3782e+22, 0.0000e+00]])


In [3]:
# 무작위로 초기화된 행렬
x = torch.rand(5,3)
print(x)

tensor([[0.2114, 0.7198, 0.9972],
        [0.3250, 0.9567, 0.4313],
        [0.9646, 0.5277, 0.6810],
        [0.0017, 0.8078, 0.2386],
        [0.9974, 0.1203, 0.1124]])


In [7]:
x.size()

torch.Size([5, 3])

### Operation

In [8]:
y = torch.rand(5, 3)
x + y

tensor([[0.2299, 1.0067, 1.5119],
        [0.8962, 0.9862, 1.0004],
        [1.0255, 1.4311, 1.5480],
        [0.5794, 1.3081, 0.9423],
        [1.2768, 0.6511, 0.8947]])

In [9]:
torch.add(x, y)

tensor([[0.2299, 1.0067, 1.5119],
        [0.8962, 0.9862, 1.0004],
        [1.0255, 1.4311, 1.5480],
        [0.5794, 1.3081, 0.9423],
        [1.2768, 0.6511, 0.8947]])

In [10]:
# 결과tensor를 인자로 제공
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.2299, 1.0067, 1.5119],
        [0.8962, 0.9862, 1.0004],
        [1.0255, 1.4311, 1.5480],
        [0.5794, 1.3081, 0.9423],
        [1.2768, 0.6511, 0.8947]])


In [11]:
# in-place
# y에 x 더하기
y.add_(x)
print(y)

tensor([[0.2299, 1.0067, 1.5119],
        [0.8962, 0.9862, 1.0004],
        [1.0255, 1.4311, 1.5480],
        [0.5794, 1.3081, 0.9423],
        [1.2768, 0.6511, 0.8947]])


### indexing

In [13]:
print(y[:,1]) # 2번째 column vector

tensor([1.0067, 0.9862, 1.4311, 1.3081, 0.6511])


In [14]:
# torch.view : size, shape 변경하고 싶을때 사용
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # (2,8)
print(y, "\n", z)

tensor([-7.6885e-01,  2.7015e-01,  1.0994e+00,  6.3074e-01,  1.8484e-01,
        -7.9511e-01,  1.2700e+00, -1.8223e-01,  1.3853e+00, -9.9578e-01,
        -8.6628e-02,  1.2138e+00,  6.0309e-01,  1.2363e-03, -8.4605e-01,
         1.0622e+00]) 
 tensor([[-7.6885e-01,  2.7015e-01,  1.0994e+00,  6.3074e-01,  1.8484e-01,
         -7.9511e-01,  1.2700e+00, -1.8223e-01],
        [ 1.3853e+00, -9.9578e-01, -8.6628e-02,  1.2138e+00,  6.0309e-01,
          1.2363e-03, -8.4605e-01,  1.0622e+00]])
